version: '3.9'

services:
  go_tutorial_app:
    container_name: go_tutorial_app
    image: golang:1.23-alpine
    build: .
    environment:
      DATABASE_URL: "host=go_tutorial_db user=root password=admin dbname=go_tutorial sslmode=disable"
    ports:
      - "9999:9999"
    depends_on:
      - go_tutorial_db
  go_tutorial_db:
    container_name: go_tutorial_db
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: root
      POSTGRES_DB: go_tutorial
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}